name: Deploiement de app s3

#on: [push] #toute les branches
on:
  push:
    branches: 
      - main #uniquement sur la branche main

jobs:
  deployment: #le nom quon donne au job
    runs-on: ubuntu-latest #instances
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List directory
      run: |
        ls -la

