name: Deploiement de app s3

#on: [push] #toute les branches
on:
  push:
    branches: 
      - main #uniquement sur la branche main

jobs:
  deployment: #le nom quon donne au job
    runs-on: ubuntu-latest #instances
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: List directory
    #   run: |
    #     ls -la

    # - name: Create new file
    #   run: |
    #     touch newfile.txt

    # - name: Lister a nouveau les fichiers et dossiers
    #   run: |
    #     ls -la

    - name: Install AWS CLI 2
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install awscli

    - name: Configure AWS credentials
      run: |
        # variable --> ${{ env.AWS_ACCESS_KEY_ID}}
        # secrets --> ${{ env.AWS_SECRET_ACCESS_KE}}

        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region eu-west-3